package com.navercorp.cubridqa.builder.exec;

/**
 * Generates the bash scripts used by the SQL Docker executor.
 *
 * Three scripts cooperate inside a container:
 *  - sql_env_setup.sh  : provisions CUBRID once per container (conf overrides via
 *                        CTP's ini.sh, createdb, stored procedures, server/broker
 *                        start, Function_Db dburl rewrite). Replicates the
 *                        provisioning steps of CTP/sql/bin/run.sh and the shipped
 *                        conf/sql.conf defaults. Writes /workspace/sql_env.sh and
 *                        /workspace/READY on success.
 *  - sql_run_case.sh   : executes ONE case against the already-running DB by
 *                        invoking CTP's ConsoleAgent directly (our own built-in
 *                        single-case runner — no external run_sql.sh / PR needed;
 *                        the runCQT + ?db= entry point is standard in CTP develop),
 *                        then collects the expected/actual/diff artifacts under
 *                        /workspace/results/<slot>/attempt_<n>/. Never exits
 *                        non-zero for a case verdict — the verdict is written to
 *                        status.line (ConsoleAgent's exit code is unreliable: it
 *                        returns 0 even on [NOK]).
 *  - per-case wrapper  : setup + one case + workspace ownership fix, for the
 *                        one-container-per-case execution mode.
 */
public class SqlScriptFactory {

    public static final String TESTCASE_MOUNT = EnvScriptFactory.TESTCASE_MOUNT;
    public static final String CTP_HOME_IN_CONTAINER = "/workspace/CTP";
    public static final String READY_MARKER = "READY";

    /**
     * Parameters for DB provisioning inside the container.
     *
     * Provisioning defaults come from the CTP payload's own conf/sql.conf at
     * runtime (i.e. whatever latest develop ships), exactly like ctp.sh's
     * run.sh. The nullable fields here are explicit tester.conf overrides;
     * null means "follow the payload's sql.conf".
     */
    public static class SqlEnvSettings {
        public final String dbName;
        public final String dbCharsetOverride;    // null → sql.conf db_charset (fallback en_US.iso88591)
        public final String createdbOptsOverride; // null → sql.conf cubrid_createdb_opts
        public final boolean loadStoredProcedures;
        public final Boolean needMakeLocaleOverride; // null → sql.conf need_make_locale (default yes)
        public final Boolean haModeOverride;         // null → sql.conf [sql/cubrid.conf] ha_mode
        public final String expectedBuildVersion;

        public SqlEnvSettings(String dbName, String dbCharsetOverride, String createdbOptsOverride,
                              boolean loadStoredProcedures, Boolean needMakeLocaleOverride, Boolean haModeOverride,
                              String expectedBuildVersion) {
            this.dbName = dbName;
            this.dbCharsetOverride = dbCharsetOverride;
            this.createdbOptsOverride = createdbOptsOverride;
            this.loadStoredProcedures = loadStoredProcedures;
            this.needMakeLocaleOverride = needMakeLocaleOverride;
            this.haModeOverride = haModeOverride;
            this.expectedBuildVersion = expectedBuildVersion;
        }
    }

    public static String createEnvSetupScript(SqlEnvSettings s) {
        String ctpHome = CTP_HOME_IN_CONTAINER;
        StringBuilder sc = new StringBuilder();
        sc.append("#!/bin/bash\n");
        sc.append("# Generated by builder-tester: provisions CUBRID for SQL testcase execution.\n");
        sc.append("set -e\n\n");

        sc.append("export TESTCASE_ROOT=\"").append(TESTCASE_MOUNT).append("\"\n");
        sc.append("if [ ! -d \"$TESTCASE_ROOT\" ]; then\n");
        sc.append("  echo \"ERROR: SQL testcase mount '$TESTCASE_ROOT' is unavailable\" >&2\n");
        sc.append("  exit 2\n");
        sc.append("fi\n");
        sc.append("export CTP_HOME=\"").append(ctpHome).append("\"\n");
        sc.append("if [ ! -d \"$CTP_HOME/sql/lib\" ]; then\n");
        sc.append("  echo \"ERROR: staged CTP is invalid (missing $CTP_HOME/sql/lib)\" >&2\n");
        sc.append("  exit 2\n");
        sc.append("fi\n\n");

        sc.append("# CUBRID is pre-installed at /opt/cubrid in the per-commit test image;\n");
        sc.append("# bind it at $HOME/CUBRID like the shell executor does.\n");
        sc.append("CUBRID_INSTALL_ROOT=\"/opt/cubrid\"\n");
        sc.append("CUBRID_HOME=\"$HOME/CUBRID\"\n");
        sc.append("if [ -L \"$CUBRID_HOME\" ]; then rm -f \"$CUBRID_HOME\"; fi\n");
        sc.append("mkdir -p \"$CUBRID_HOME\"\n");
        sc.append("if grep -qs \" $CUBRID_HOME \" /proc/mounts; then\n");
        sc.append("  :\n");
        sc.append("elif ! mount --bind \"$CUBRID_INSTALL_ROOT\" \"$CUBRID_HOME\" 2>/dev/null; then\n");
        sc.append("  echo \"WARNING: bind /opt/cubrid -> $CUBRID_HOME failed; using symlink fallback\" >&2\n");
        sc.append("  rmdir \"$CUBRID_HOME\" 2>/dev/null || true\n");
        sc.append("  ln -s \"$CUBRID_INSTALL_ROOT\" \"$CUBRID_HOME\" 2>/dev/null || true\n");
        sc.append("fi\n");
        sc.append("export CUBRID=\"$CUBRID_HOME\"\n");
        sc.append("export CUBRID_DATABASES=\"$CUBRID/databases\"\n");
        sc.append("export SHELL=/bin/bash\n");
        sc.append("export PATH=\"$CUBRID/bin:").append(ctpHome).append("/bin:").append(ctpHome).append("/common/script:$PATH\"\n");
        sc.append("export LD_LIBRARY_PATH=\"$CUBRID/lib:$CUBRID/cci/lib:$CUBRID/lib64:").append(ctpHome).append("/common/lib:$LD_LIBRARY_PATH\"\n\n");

        sc.append("# Locale/timezone environment expected by SQL testcases (see doc/sql_guide.md)\n");
        sc.append("export TZ='Asia/Seoul'\n");
        sc.append("export LC_ALL=en_US.UTF-8\n");
        sc.append("export CUBRID_LANG=en_US\n\n");

        sc.append("# JAVA_HOME is required by CTP (ConsoleAgent, ini.sh) and java_stored_procedure\n");
        sc.append("if [ -z \"$JAVA_HOME\" ]; then\n");
        sc.append("  JAVA_BIN=$(command -v java || true)\n");
        sc.append("  if [ -n \"$JAVA_BIN\" ]; then\n");
        sc.append("    export JAVA_HOME=$(dirname \"$(dirname \"$(readlink -f \"$JAVA_BIN\")\")\")\n");
        sc.append("  fi\n");
        sc.append("fi\n");
        sc.append("if [ -z \"$JAVA_HOME\" ] || [ ! -x \"$JAVA_HOME/bin/java\" ]; then\n");
        sc.append("  echo \"ERROR: JAVA_HOME could not be determined in the test image\" >&2\n");
        sc.append("  exit 2\n");
        sc.append("fi\n");
        sc.append("for d in \"$JAVA_HOME/jre/lib/amd64\" \"$JAVA_HOME/jre/lib/amd64/server\" \"$JAVA_HOME/lib\" \"$JAVA_HOME/lib/server\"; do\n");
        sc.append("  [ -d \"$d\" ] && export LD_LIBRARY_PATH=\"$d:$LD_LIBRARY_PATH\"\n");
        sc.append("done\n\n");

        sc.append("echo \"Verifying CUBRID installation...\"\n");
        sc.append("if ! cubrid_rel; then\n");
        sc.append("  echo \"ERROR: CUBRID verification failed\" >&2\n");
        sc.append("  exit 1\n");
        sc.append("fi\n\n");

        if (s.expectedBuildVersion != null && !s.expectedBuildVersion.isEmpty()) {
            sc.append("INSTALLED_VER=$(cubrid_rel 2>/dev/null | sed -n 's/.*-\\([a-z0-9]\\{7\\}\\))/\\1/p' | head -1)\n");
            sc.append("if [[ \"$INSTALLED_VER\" == *\"0000000\"* ]]; then\n");
            sc.append("  echo \"Actual build commit hash: ").append(s.expectedBuildVersion).append(". To guarantee your build's commit hash, please build CUBRID with ccache off.\"\n");
            sc.append("elif [[ \"$INSTALLED_VER\" != *\"").append(s.expectedBuildVersion).append("\"* ]]; then\n");
            sc.append("  echo \"WARNING: Expected build commit hash ").append(s.expectedBuildVersion)
              .append(" not found in CUBRID build version (cubrid_rel)\"\n");
            sc.append("fi\n\n");
        }

        sc.append("INI() { sh \"$CTP_HOME/bin/ini.sh\" \"$@\"; }\n\n");

        sc.append("# Resolve provisioning settings from the CTP payload's own conf/sql.conf so the\n");
        sc.append("# configuration always tracks latest develop (mirrors run.sh do_configure).\n");
        sc.append("# Explicit tester.conf overrides win when set.\n");
        sc.append("SQL_MAIN_CONF=\"$CTP_HOME/conf/sql.conf\"\n");
        sc.append("if [ ! -f \"$SQL_MAIN_CONF\" ]; then\n");
        sc.append("  echo \"ERROR: staged CTP is missing conf/sql.conf\" >&2\n");
        sc.append("  exit 2\n");
        sc.append("fi\n");
        sc.append("DB_CHARSET=\"").append(s.dbCharsetOverride == null ? "" : s.dbCharsetOverride).append("\"\n");
        sc.append("[ -z \"$DB_CHARSET\" ] && DB_CHARSET=$(INI -s sql \"$SQL_MAIN_CONF\" db_charset 2>/dev/null || true)\n");
        sc.append("[ -z \"$DB_CHARSET\" ] && DB_CHARSET=en_US.iso88591\n");
        sc.append("export CUBRID_CHARSET=\"$DB_CHARSET\"\n");
        sc.append("CREATEDB_OPTS=\"").append(s.createdbOptsOverride == null ? "" : s.createdbOptsOverride).append("\"\n");
        sc.append("[ -z \"$CREATEDB_OPTS\" ] && CREATEDB_OPTS=$(INI -s sql \"$SQL_MAIN_CONF\" cubrid_createdb_opts 2>/dev/null || true)\n");
        sc.append("NEED_MAKE_LOCALE=\"").append(s.needMakeLocaleOverride == null ? "" : (s.needMakeLocaleOverride ? "yes" : "no")).append("\"\n");
        sc.append("[ -z \"$NEED_MAKE_LOCALE\" ] && NEED_MAKE_LOCALE=$(INI -s sql \"$SQL_MAIN_CONF\" need_make_locale 2>/dev/null || true)\n");
        sc.append("[ -z \"$NEED_MAKE_LOCALE\" ] && NEED_MAKE_LOCALE=yes\n");
        sc.append("# jdbc client config (autocommit/holdcas/run_mode/reset SQL) — tracks the payload's sql.conf\n");
        sc.append("JDBC_CONFIG_FILE=$(INI -s sql \"$SQL_MAIN_CONF\" jdbc_config_file 2>/dev/null || true)\n");
        sc.append("[ -z \"$JDBC_CONFIG_FILE\" ] && JDBC_CONFIG_FILE=test_default.xml\n\n");

        sc.append("# Apply the [sql/cubrid.conf] / broker / ha sections from the payload's sql.conf\n");
        sc.append("# (mirrors run.sh config_cubrid_without_ha / config_cubrid_ha). Fixed ports and\n");
        sc.append("# shm ids are safe: each container has its own net/IPC namespace.\n");
        sc.append("CUBRID_CONF_PARA=$(INI -s \"sql/cubrid.conf\" --separator=\"||\" \"$SQL_MAIN_CONF\" 2>/dev/null || true)\n");
        sc.append("if [ -n \"$CUBRID_CONF_PARA\" ]; then\n");
        sc.append("  INI -s common -u \"$CUBRID_CONF_PARA\" \"$CUBRID/conf/cubrid.conf\"\n");
        sc.append("fi\n");
        if (s.haModeOverride != null) {
            sc.append("INI -s common -u \"ha_mode=").append(s.haModeOverride ? "yes" : "no")
              .append("\" \"$CUBRID/conf/cubrid.conf\"\n");
        }
        sc.append("INI -s service -u \"service=server,broker\" \"$CUBRID/conf/cubrid.conf\"\n");
        sc.append("BROKER_SHM_PARA=$(INI -s \"sql/cubrid_broker.conf/broker\" --separator=\"||\" \"$SQL_MAIN_CONF\" 2>/dev/null || true)\n");
        sc.append("if [ -n \"$BROKER_SHM_PARA\" ]; then\n");
        sc.append("  INI -s broker -u \"$BROKER_SHM_PARA\" \"$CUBRID/conf/cubrid_broker.conf\"\n");
        sc.append("fi\n");
        sc.append("QUERY_EDITOR_PARA=$(INI -s \"sql/cubrid_broker.conf/%query_editor\" --separator=\"||\" \"$SQL_MAIN_CONF\" 2>/dev/null || true)\n");
        sc.append("if [ -n \"$QUERY_EDITOR_PARA\" ] && grep -q '\\[%query_editor\\]' \"$CUBRID/conf/cubrid_broker.conf\"; then\n");
        sc.append("  INI -s \"%query_editor\" -u \"$QUERY_EDITOR_PARA\" \"$CUBRID/conf/cubrid_broker.conf\"\n");
        sc.append("fi\n");
        sc.append("BROKER1_PARA=$(INI -s \"sql/cubrid_broker.conf/%BROKER1\" --separator=\"||\" \"$SQL_MAIN_CONF\" 2>/dev/null || true)\n");
        sc.append("if [ -n \"$BROKER1_PARA\" ] && grep -q '\\[%BROKER1\\]' \"$CUBRID/conf/cubrid_broker.conf\"; then\n");
        sc.append("  INI -s \"%BROKER1\" -u \"$BROKER1_PARA\" \"$CUBRID/conf/cubrid_broker.conf\"\n");
        sc.append("fi\n\n");

        sc.append("# HA applies only when cubrid.conf ended up with ha_mode on/yes AND the build\n");
        sc.append("# supports heartbeat (mirrors run.sh)\n");
        sc.append("HA_CNT=$(grep -v '#' \"$CUBRID/conf/cubrid.conf\" | grep ha_mode | grep -Ec 'on|yes' || true)\n");
        sc.append("IS_SUPPORT_HA=$(cubrid 2>&1 | grep -c heartbeat || true)\n");
        sc.append("if [ \"$HA_CNT\" -gt 0 ] && [ \"$IS_SUPPORT_HA\" -eq 0 ]; then\n");
        sc.append("  echo \"WARNING: build has no heartbeat support; disabling ha_mode for this run\"\n");
        sc.append("  INI -s common -u \"ha_mode=no\" \"$CUBRID/conf/cubrid.conf\"\n");
        sc.append("  HA_CNT=0\n");
        sc.append("fi\n");
        sc.append("if [ \"$HA_CNT\" -gt 0 ]; then\n");
        sc.append("  HA_MODE=yes\n");
        sc.append("  CUBRID_HA_PARA=$(INI -s \"sql/cubrid_ha.conf\" --separator=\"||\" \"$SQL_MAIN_CONF\" 2>/dev/null || true)\n");
        sc.append("  if [ -n \"$CUBRID_HA_PARA\" ]; then\n");
        sc.append("    INI -s common -u \"ha_db_list=").append(s.dbName).append("||$CUBRID_HA_PARA\" \"$CUBRID/conf/cubrid_ha.conf\"\n");
        sc.append("  else\n");
        sc.append("    INI -s common -u \"ha_db_list=").append(s.dbName).append("\" \"$CUBRID/conf/cubrid_ha.conf\"\n");
        sc.append("  fi\n");
        sc.append("else\n");
        sc.append("  HA_MODE=no\n");
        sc.append("fi\n\n");

        sc.append("SUPPORT_JAVASP=$(cubrid 2>&1 | grep -cw javasp || true)\n\n");

        sc.append("# Compile all locales when need_make_locale=yes (required by i18n/collation suites)\n");
        sc.append("if [ \"$NEED_MAKE_LOCALE\" = \"yes\" ]; then\n");
        sc.append("  if [ -f \"$CUBRID/bin/make_locale.sh\" ] && [ -f \"$CUBRID/conf/cubrid_locales.all.txt\" ]; then\n");
        sc.append("    echo \"make locale now\"\n");
        sc.append("    mv \"$CUBRID/conf/cubrid_locales.txt\" \"$CUBRID/conf/cubrid_locales_bak.txt\" 2>/dev/null || true\n");
        sc.append("    cp \"$CUBRID/conf/cubrid_locales.all.txt\" \"$CUBRID/conf/cubrid_locales.txt\"\n");
        sc.append("    DBG_CNT=$(cubrid_rel | grep -c debug || true)\n");
        sc.append("    (cd \"$CUBRID/bin\" && if [ \"$DBG_CNT\" -gt 0 ]; then sh make_locale.sh -t 64 -m debug; else sh make_locale.sh -t 64; fi)\n");
        sc.append("  else\n");
        sc.append("    echo \"WARNING: make_locale.sh not available; skipping locale compilation\"\n");
        sc.append("  fi\n");
        sc.append("fi\n\n");

        sc.append("echo \"MAKE ").append(s.dbName).append(" DATABASE (default size)...\"\n");
        sc.append("mkdir -p \"$CUBRID/databases/").append(s.dbName).append("\"\n");
        sc.append("cd \"$CUBRID/databases/").append(s.dbName).append("\"\n");
        sc.append("echo \"cubrid createdb $CREATEDB_OPTS ").append(s.dbName).append(" $DB_CHARSET\"\n");
        sc.append("cubrid createdb $CREATEDB_OPTS ").append(s.dbName).append(" $DB_CHARSET\n\n");

        if (s.loadStoredProcedures) {
            sc.append("# Load Java stored procedure classes (needed by _08_javasp and friends)\n");
            sc.append("if [ -d \"$CTP_HOME/sql/function/stored_procedure/src\" ]; then\n");
            sc.append("  echo \"Load Java Stored Procedure Classes\"\n");
            sc.append("  (cd \"$CTP_HOME/sql/function/stored_procedure/src\" \\\n");
            sc.append("    && rm -f *.class \\\n");
            sc.append("    && \"$JAVA_HOME/bin/javac\" -cp \"$CUBRID/jdbc/cubrid_jdbc.jar\" *.java \\\n");
            sc.append("    && for clz in *.class; do echo \"Load ${clz}...\"; loadjava ").append(s.dbName).append(" \"$clz\" >/dev/null 2>&1 || echo \"WARNING: loadjava failed for $clz\"; done \\\n");
            sc.append("    && rm -f *.class) || echo \"WARNING: stored procedure load failed\"\n");
            sc.append("fi\n\n");
        }

        sc.append("echo \"start database ").append(s.dbName).append("\"\n");
        sc.append("cubrid service stop >/dev/null 2>&1 || true\n");
        sc.append("sleep 1\n");
        sc.append("cubrid service start\n");
        sc.append("sleep 1\n");
        sc.append("if [ \"$HA_MODE\" = \"yes\" ]; then\n");
        sc.append("  cubrid hb start ").append(s.dbName).append("\n");
        sc.append("else\n");
        sc.append("  cubrid server start ").append(s.dbName).append("\n");
        sc.append("fi\n");
        sc.append("if [ \"$SUPPORT_JAVASP\" -gt 0 ]; then\n");
        sc.append("  cubrid javasp start ").append(s.dbName).append(" >/dev/null 2>&1 || true\n");
        sc.append("fi\n");
        sc.append("cubrid broker restart\n");
        sc.append("sleep 2\n\n");

        sc.append("# Wait for server + broker to become active (mirrors run.sh check_status)\n");
        sc.append("if [ \"$HA_MODE\" = \"yes\" ]; then\n");
        sc.append("  m=0\n");
        sc.append("  res=$(cubrid changemode ").append(s.dbName).append(" 2>&1 | grep -e active -e 'not configured for HA' || true)\n");
        sc.append("  while [ -z \"$res\" ]; do\n");
        sc.append("    if [ $m -gt 50 ]; then echo \"ERROR: DB did not become active\" >&2; exit 1; fi\n");
        sc.append("    sleep 2\n");
        sc.append("    echo \"waiting for ").append(s.dbName).append(" become active...\"\n");
        sc.append("    res=$(cubrid changemode ").append(s.dbName).append(" 2>&1 | grep active || true)\n");
        sc.append("    m=$((m + 1))\n");
        sc.append("  done\n");
        sc.append("else\n");
        sc.append("  m=0\n");
        sc.append("  server_status=$(cubrid server status | grep -c \"").append(s.dbName).append("\" || true)\n");
        sc.append("  broker_status=$(cubrid broker status 2>/dev/null | grep -c PID || true)\n");
        sc.append("  while [ \"$server_status\" -ne 1 ] || [ \"$broker_status\" -eq 0 ]; do\n");
        sc.append("    if [ $m -gt 50 ]; then echo \"ERROR: server/broker did not become active\" >&2; exit 1; fi\n");
        sc.append("    sleep 2\n");
        sc.append("    echo \"waiting for server and broker become active...\"\n");
        sc.append("    server_status=$(cubrid server status | grep -c \"").append(s.dbName).append("\" || true)\n");
        sc.append("    broker_status=$(cubrid broker status 2>/dev/null | grep -c PID || true)\n");
        sc.append("    m=$((m + 1))\n");
        sc.append("  done\n");
        sc.append("fi\n\n");

        sc.append("# Point Function_Db/<db>_qa.xml at the live broker port (mirrors run.sh config_qa_tool)\n");
        sc.append("QA_DB_XML=\"$CTP_HOME/sql/configuration/Function_Db/").append(s.dbName).append("_qa.xml\"\n");
        sc.append("if [ ! -f \"$QA_DB_XML\" ]; then\n");
        sc.append("  echo \"ERROR: missing $QA_DB_XML (db name '").append(s.dbName).append("' needs a Function_Db config)\" >&2\n");
        sc.append("  exit 2\n");
        sc.append("fi\n");
        sc.append("BROKER_PORT=$(awk '/SERVICE[[:space:]]*=[[:space:]]*ON/, /BROKER_PORT/' \"$CUBRID/conf/cubrid_broker.conf\" | grep BROKER_PORT | grep -v '#' | awk -F '=' '{print $2}' | head -1 | tr -d ' ' | tr -d '\\r')\n");
        sc.append("[ -z \"$BROKER_PORT\" ] && BROKER_PORT=33120\n");
        sc.append("sed -i \"s#<dburl>.*</dburl>#<dburl>jdbc:cubrid:localhost:${BROKER_PORT}:").append(s.dbName).append(":::</dburl>#g\" \"$QA_DB_XML\"\n");
        sc.append("sed -i \"s#<version>.*</version>#<version>Main</version>#g\" \"$QA_DB_XML\"\n\n");

        sc.append("# Write local.properties (gitignored upstream, so absent from the payload;\n");
        sc.append("# ConsoleAgent hard-requires it and uses dbversion/dbbuildnumber in result dir names)\n");
        sc.append("CUBRID_VER=$(cubrid_rel | grep CUBRID | awk -F'(' '{print $2}' | awk -F')' '{print $1}')\n");
        sc.append("VER_PREFIX=${CUBRID_VER%.*}\n");
        sc.append("VER_BUILD=$(echo \"$CUBRID_VER\" | cut -d . -f 4)\n");
        sc.append("printf 'dbversion=%s\\ndbbuildnumber=%s\\n' \"${VER_PREFIX:-unknown}\" \"${VER_BUILD:-0}\" > \"$CTP_HOME/sql/configuration/local.properties\"\n\n");

        sc.append("# Snapshot the environment for later docker exec sessions (sql_run_case.sh sources this)\n");
        sc.append("cat > /workspace/sql_env.sh <<EOS\n");
        sc.append("export CUBRID=\"$CUBRID\"\n");
        sc.append("export CUBRID_DATABASES=\"$CUBRID_DATABASES\"\n");
        sc.append("export CTP_HOME=\"$CTP_HOME\"\n");
        sc.append("export TESTCASE_ROOT=\"$TESTCASE_ROOT\"\n");
        sc.append("export JAVA_HOME=\"$JAVA_HOME\"\n");
        sc.append("export PATH=\"$PATH\"\n");
        sc.append("export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH\"\n");
        sc.append("export TZ='Asia/Seoul'\n");
        sc.append("export LC_ALL=en_US.UTF-8\n");
        sc.append("export CUBRID_CHARSET=\"$CUBRID_CHARSET\"\n");
        sc.append("export CUBRID_LANG=en_US\n");
        sc.append("export SQL_DB_NAME=\"").append(s.dbName).append("\"\n");
        sc.append("export SQL_JDBC_CONFIG_FILE=\"$JDBC_CONFIG_FILE\"\n");
        sc.append("EOS\n");
        sc.append("chmod +x /workspace/sql_env.sh\n");
        sc.append("touch /workspace/").append(READY_MARKER).append("\n");
        sc.append("echo \"SQL_ENV_READY\"\n");
        return sc.toString();
    }

    /**
     * Generic single-case runner: usage sql_run_case.sh <case-rel-path> <attempt> <slot>.
     * Requires a container already provisioned by sql_env_setup.sh. Writes
     * /workspace/results/<slot>/attempt_<n>/{status.line,console.log,expected.answer,
     * actual.result,answer.diff}. Always exits 0 unless the environment is broken;
     * the verdict lives in status.line (ConsoleAgent exits 0 even on [NOK]).
     *
     * The case is executed by invoking CTP's ConsoleAgent runCQT entry point
     * directly (standard in CTP develop) — our own single-case runner, with no
     * dependency on an external wrapper script or upstream PR.
     */
    public static String createCaseRunScript(int caseTimeoutSec) {
        StringBuilder sc = new StringBuilder();
        sc.append("#!/bin/bash\n");
        sc.append("# Generated by builder-tester: runs one SQL case via CTP ConsoleAgent (built-in runner).\n");
        sc.append("REL=\"$1\"\n");
        sc.append("ATTEMPT=\"${2:-1}\"\n");
        sc.append("SLOT=\"${3:-case}\"\n");
        sc.append("if [ ! -f /workspace/sql_env.sh ]; then\n");
        sc.append("  echo \"SQLCASE_RESULT status=error reason=env_not_provisioned\"\n");
        sc.append("  exit 3\n");
        sc.append("fi\n");
        sc.append("source /workspace/sql_env.sh\n");
        sc.append("OUT=\"/workspace/results/${SLOT}/attempt_${ATTEMPT}\"\n");
        sc.append("mkdir -p \"$OUT\"\n");
        sc.append("finish() {\n");
        sc.append("  echo \"$1\" | tee \"$OUT/status.line\"\n");
        sc.append("  exit 0\n");
        sc.append("}\n\n");

        sc.append("# Case path may be relative (under the mounted testcases tree) or absolute\n");
        sc.append("# (custom SQL mode materializes the case under /workspace).\n");
        sc.append("case \"$REL\" in\n");
        sc.append("  /*) CASE_FILE=\"$REL\" ;;\n");
        sc.append("  *)  CASE_FILE=\"$TESTCASE_ROOT/$REL\" ;;\n");
        sc.append("esac\n");
        sc.append("if [ ! -f \"$CASE_FILE\" ]; then\n");
        sc.append("  finish \"SQLCASE_RESULT status=error rc=0 core=0 reason=case_not_found\"\n");
        sc.append("fi\n");
        sc.append("CASE_BASE=$(basename \"${CASE_FILE%.sql}\")\n");
        sc.append("CASE_DIR=$(dirname \"$CASE_FILE\")\n");
        sc.append("ANSWER_FILE=\"$(dirname \"$CASE_DIR\")/answers/${CASE_BASE}.answer\"\n");
        sc.append("if [ ! -f \"$ANSWER_FILE\" ]; then\n");
        sc.append("  finish \"SQLCASE_RESULT status=notrun rc=0 core=0 reason=missing_answer\"\n");
        sc.append("fi\n");
        sc.append("cp \"$ANSWER_FILE\" \"$OUT/expected.answer\" 2>/dev/null || true\n\n");

        sc.append("# Built-in single-case runner: invoke CTP's ConsoleAgent directly against the\n");
        sc.append("# running DB (equivalent to the historical run_sql.sh wrapper, but self-contained).\n");
        sc.append("CPCLASSES=\"\"\n");
        sc.append("shopt -s nullglob\n");
        sc.append("for jar in \"$CTP_HOME/sql/lib/\"*.jar; do CPCLASSES=\"${CPCLASSES:+$CPCLASSES:}$jar\"; done\n");
        sc.append("shopt -u nullglob\n");
        sc.append("if [ -z \"$CPCLASSES\" ]; then\n");
        sc.append("  finish \"SQLCASE_RESULT status=error rc=0 core=0 reason=no_ctp_jars\"\n");
        sc.append("fi\n");
        sc.append("JDBC_CONFIG_FILE=\"${SQL_JDBC_CONFIG_FILE:-test_default.xml}\"\n");
        sc.append("timeout ").append(Math.max(10, caseTimeoutSec))
          .append(" \"$JAVA_HOME/bin/java\" -classpath \"$CPCLASSES\" \\\n");
        sc.append("  com.navercorp.cubridqa.cqt.console.ConsoleAgent \\\n");
        sc.append("  runCQT sql sql 64 \"$JDBC_CONFIG_FILE\" \\\n");
        sc.append("  \"${CASE_FILE}?db=${SQL_DB_NAME}_qa\" > \"$OUT/console.log\" 2>&1\n");
        sc.append("RC=$?\n");
        sc.append("if [ $RC -eq 124 ] || [ $RC -eq 137 ]; then\n");
        sc.append("  finish \"SQLCASE_RESULT status=timeout rc=$RC core=0 reason=case_timeout_").append(Math.max(10, caseTimeoutSec)).append("s\"\n");
        sc.append("fi\n\n");

        sc.append("# The verdict is only reliable from the console output ([OK]/[NOK])\n");
        sc.append("VERDICT=$(grep -Eo '\\[(OK|NOK)\\]' \"$OUT/console.log\" | tail -1)\n");
        sc.append("RESULT_ROOT=$(grep -m1 '^Result Root Dir:' \"$OUT/console.log\" | sed 's/^Result Root Dir://' | tr -d '\\r')\n\n");

        sc.append("CORE_FLAG=0\n");
        sc.append("CORES=$(find \"$CUBRID\" -maxdepth 2 \\( -name 'core' -o -name 'core.*' \\) -type f 2>/dev/null | head -5)\n");
        sc.append("if [ -n \"$CORES\" ]; then\n");
        sc.append("  CORE_FLAG=1\n");
        sc.append("  echo \"$CORES\" > \"$OUT/core.list\"\n");
        sc.append("fi\n\n");

        sc.append("if [ \"$VERDICT\" = \"[NOK]\" ]; then\n");
        sc.append("  # CTP saved the actual output (and the used answer) under the result root\n");
        sc.append("  if [ -n \"$RESULT_ROOT\" ] && [ -d \"$RESULT_ROOT\" ]; then\n");
        sc.append("    ACTUAL=$(find \"$RESULT_ROOT\" -name \"${CASE_BASE}.result\" | head -1)\n");
        sc.append("    USED_ANSWER=$(find \"$RESULT_ROOT\" -name \"${CASE_BASE}.answer\" | head -1)\n");
        sc.append("    [ -n \"$ACTUAL\" ] && cp \"$ACTUAL\" \"$OUT/actual.result\"\n");
        sc.append("    [ -n \"$USED_ANSWER\" ] && cp \"$USED_ANSWER\" \"$OUT/expected.answer\"\n");
        sc.append("  fi\n");
        sc.append("  if [ -f \"$OUT/actual.result\" ]; then\n");
        sc.append("    # Normalize CRs only; CTP's comparison also ignores newlines, so a\n");
        sc.append("    # near-empty diff means a line-structure-only difference.\n");
        sc.append("    tr -d '\\r' < \"$OUT/expected.answer\" > \"$OUT/.expected.norm\" 2>/dev/null || true\n");
        sc.append("    tr -d '\\r' < \"$OUT/actual.result\" > \"$OUT/.actual.norm\" 2>/dev/null || true\n");
        sc.append("    diff -u --label expected.answer --label actual.result \"$OUT/.expected.norm\" \"$OUT/.actual.norm\" > \"$OUT/answer.diff\" || true\n");
        sc.append("    rm -f \"$OUT/.expected.norm\" \"$OUT/.actual.norm\"\n");
        sc.append("  fi\n");
        sc.append("  finish \"SQLCASE_RESULT status=nok rc=$RC core=$CORE_FLAG\"\n");
        sc.append("elif [ \"$VERDICT\" = \"[OK]\" ]; then\n");
        sc.append("  finish \"SQLCASE_RESULT status=ok rc=$RC core=$CORE_FLAG\"\n");
        sc.append("else\n");
        sc.append("  finish \"SQLCASE_RESULT status=error rc=$RC core=$CORE_FLAG reason=no_verdict_in_console\"\n");
        sc.append("fi\n");
        return sc.toString();
    }

    /**
     * One-container-per-case wrapper: provision, run the single case, fix ownership.
     */
    public static String createPerCaseScript(String caseRelPath, int attemptNumber) {
        StringBuilder sc = new StringBuilder();
        sc.append("#!/bin/bash\n");
        sc.append("# Generated by builder-tester: per-case SQL execution (setup + one case).\n");
        sc.append("set -e\n");
        sc.append("bash /workspace/sql_env_setup.sh\n");
        sc.append("set +e\n");
        sc.append("bash /workspace/sql_run_case.sh '").append(caseRelPath.replace("'", "'\\''")).append("' ")
          .append(attemptNumber).append(" case\n");
        sc.append("CASE_RC=$?\n");
        sc.append("if [ -n \"$HOST_UID\" ] && [ -n \"$HOST_GID\" ]; then\n");
        sc.append("  chown -R \"$HOST_UID:$HOST_GID\" /workspace 2>/dev/null || true\n");
        sc.append("fi\n");
        sc.append("exit $CASE_RC\n");
        return sc.toString();
    }

    /**
     * Long-lived agent entrypoint (pool mode): provision, signal readiness, idle.
     */
    public static String createAgentEntryScript() {
        StringBuilder sc = new StringBuilder();
        sc.append("#!/bin/bash\n");
        sc.append("# Generated by builder-tester: SQL agent container entrypoint (pool mode).\n");
        sc.append("if bash /workspace/sql_env_setup.sh; then\n");
        sc.append("  echo \"AGENT_READY\"\n");
        sc.append("else\n");
        sc.append("  echo \"AGENT_SETUP_FAILED\" > /workspace/SETUP_FAILED\n");
        sc.append("fi\n");
        sc.append("if [ -n \"$HOST_UID\" ] && [ -n \"$HOST_GID\" ]; then\n");
        sc.append("  chown -R \"$HOST_UID:$HOST_GID\" /workspace 2>/dev/null || true\n");
        sc.append("fi\n");
        sc.append("tail -f /dev/null\n");
        return sc.toString();
    }
}
